name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '3.57.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            SUPABASE_URL
            SUPABASE_KEY
            UBIQUIBOT_PUBLIC_KEY
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          UBIQUIBOT_PUBLIC_KEY: ${{ secrets.UBIQUIBOT_PUBLIC_KEY }}
